a = ['M', 'i', 'l', 'a', 'n']
b = ['C', 'a', 'b', 'a', 'n']
print(a[0] + b[0])
print(a[0] + b[1])
print(a[0] + b[2])
print(a[0] + b[3])
print(a[0] + b[4])
print(a[1] + b[1])
print(a[1] + b[2])
print(a[1] + b[3])
print(a[1] + b[4])
print(a[2] + b[1])
print(a[2] + b[2])
print(a[2] + b[3])
print(a[2] + b[4])
print(a[3] + b[1])
print(a[3] + b[2])
print(a[3] + b[3])
print(a[3] + b[4])
print(a[4] + b[1])
print(a[4] + b[2])
print(a[4] + b[3])
print(a[4] + b[4])

